language: ruby
rvm:
 â€” 2.7.1
deploy:
  provider: cloudfoundry
  api: $API_URI
  username: $USERNAME
  password: $PASSWORD
  organization: $ORG_NAME
  space: $SPACE_TYPE_STAGING
  on:
    repo: Crown-Commercial-Service/pmp-idam
    branch: staging
  skip_cleanup: 'true'
